image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - command: mkdir -p /workspace/redis-config-cache-pod/data
  - command: redis-server /workspace/redis-config-cache-pod/redis.conf &
